import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import * as crypto from 'crypto';

/**
 * `GPL: Export AI Agent Setup` (gpl.ai.exportAgentSetup)
 *
 * 현재 워크스페이스를 "외부 AI(Claude Code) 디버깅 가능" 상태로 만든다.
 * VSIX에 동봉된 MCP 서버 번들(out/mcp/gpl-controller-mcp.cjs)을 확장
 * globalStorage(버전 무관 안정 경로)로 복사하고, 그 경로를 가리키는
 * `.mcp.json`과 제어기 안전 규칙을 담은 CLAUDE.md 섹션을 생성한다.
 *
 * 배경: ai-handoff.md §1-AH — MCP 미등록 워크스페이스에서 AI가 원시 TCP로
 * 1402를 우회 접속하려던 사고의 재발 방지책. VSIX 동봉만으로는 Claude Code에
 * 자동 등록되지 않으므로(등록 주체는 `.mcp.json`), 이 명령이 그 간극을 메운다.
 *
 * 주의: 확장 설치 경로(out/mcp/...)를 .mcp.json에 직접 쓰면 확장 업데이트 시
 * 버전 폴더가 바뀌어 조용히 깨진다. 그래서 globalStorage 복사본을 가리킨다.
 * 명령을 다시 실행하면 복사본이 최신 번들로 갱신되고, 확장 활성화 시에도 사본이 동봉 번들과
 * 다르면(sha256) 자동으로 갱신한다(GitHub #23 — 업데이트 뒤 구버전 서버가 계속 돌던 문제).
 * 번들 옆 사이드카 `gpl-controller-mcp.build.json`(버전·빌드 시각·git sha)이 "어느 번들인가"의 근거다.
 */

const MCP_SERVER_NAME = 'gpl-controller';
const BUNDLE_RELATIVE_PATH = path.join('out', 'mcp', 'gpl-controller-mcp.cjs');
const BUILD_INFO_RELATIVE_PATH = path.join('out', 'mcp', 'gpl-controller-mcp.build.json');
/** CLAUDE.md 자동 생성 블록 안의 기계 판독용 버전 표식(Check 명령이 구버전 안내를 감지하는 근거). */
const CLAUDE_SECTION_VERSION_MARK = '<!-- gpl-controller-mcp guide version:';
const CLAUDE_SECTION_BEGIN = '<!-- BEGIN gpl-controller-mcp guide (auto-generated by "GPL: Export AI Agent Setup" — 수동 편집 금지, 재실행 시 이 블록만 교체됨) -->';
const CLAUDE_SECTION_END = '<!-- END gpl-controller-mcp guide -->';
const CLAUDE_SECTION_HEADING = '## 제어기 통신 — gpl-controller MCP 도구만 사용한다 (직접 TCP 금지)';
// 수동 작성 섹션 감지용 — "## 7. 제어기 통신 — ..."처럼 번호가 붙어도 잡히도록 제목 본문만 본다
// (2026-08-05 시뮬레이션 워크스페이스에서 정확 일치 검사가 번호 접두 때문에 통과해 중복 생성된 실사례).
const CLAUDE_SECTION_TOPIC = '제어기 통신 — gpl-controller MCP 도구만 사용한다';

export interface ExportAiAgentSetupOptions {
	ip: string;
	port: number;
	projectName?: string;
}

export interface ExportAiAgentSetupResult {
	ok: boolean;
	error?: string;
	detail?: string;
	/** 생성/갱신된 파일 경로 목록 */
	written?: string[];
	/** 건너뛴 항목과 이유 (예: CLAUDE.md에 수동 작성 섹션이 이미 있음) */
	skipped?: string[];
}

function buildClaudeSection(opts: ExportAiAgentSetupOptions, extensionVersion: string): string {
	const projectLine = opts.projectName
		? `기본 프로젝트는 \`${opts.projectName}\`(도구의 project 인자 생략 시 사용).`
		: '기본 프로젝트는 `.mcp.json`의 `GPL_PROJECT` 값을 따른다.';
	return [
		CLAUDE_SECTION_BEGIN,
		`${CLAUDE_SECTION_VERSION_MARK} ${extensionVersion} -->`,
		'',
		CLAUDE_SECTION_HEADING,
		'',
		`제어기(${opts.ip}:${opts.port}, 1402 명령 콘솔)와의 모든 통신은 **\`${MCP_SERVER_NAME}\` MCP 도구로만** 한다.`,
		'PowerShell/Node/Python 등으로 **원시 TCP 소켓을 직접 여는 것을 금지**한다. 원시 소켓에는 명령 직렬화',
		'큐도, Stop/모션 안전 게이트도 없어서 추측으로 보내는 명령이 로봇 모션을 유발할 수 있다.',
		'',
		`**도구가 안 보일 때**: 서버는 이 워크스페이스의 \`.mcp.json\`에 등록되어 있고 Claude Code가 세션 시작 시`,
		'자동으로 띄운다(수동 실행·설치 불필요). `/mcp`로 연결 상태를 확인하고, 처음이면 승인 프롬프트만 수락한다.',
		'그래도 없으면 사용자에게 알리고 멈춘다 — 직접 소켓으로 우회하지 않는다.',
		'',
		'**판정 규칙**: 명령의 성공/실패는 해당 응답의 `<STATUS>`를 `</STATUS>` 종결자까지 읽고 판정한다.',
		'간접 신호(로그 파일, 침묵, 부분 응답)로 성공을 추정하지 않는다.',
		'',
		'**전형적 디버그 흐름**: `set_breakpoint(file, line)` → `start_project(stopOnEntry: true)` →',
		'`show_threads`로 정지 스레드 확인 → `show_stack` /',
		'**Compile과 Start는 한 번에 하나만**: PA 제어기의 Start는 자체적으로 Compile을 수행한다(실사용 사실 — Brooks 문서와 다름).',
		'따라서 `compile_project` 직후 `start_project`를 연속으로 보내지 않는다(컴파일 중복, 안전성 미확인). 에러만 확인할 때는',
		'`compile_project`, 실행할 때는 `start_project`만 호출한다.',
		'`eval_expression(thread, frame, expr)`로 상태 분석 → `step_thread` / `continue_thread` 반복.',
		'`Break`/`Step` 뒤에는 `show_thread`로 실제 정지를 확인한 다음 스택/변수를 읽는다(접수≠완료).',
		projectLine,
		'',
		'**중단점 워크플로**: VS Code 설정 `gpl.controller.syncEditorBreakpoints`가 켜져 있으면 사용자가',
		'에디터에서 찍은 중단점이 제어기에 자동 반영된다(에디터가 단일 원본) — 이때는 `set_breakpoint` 대신',
		'사용자에게 에디터에서 중단점을 관리해 달라고 요청하는 것이 UI와 일치한다. `set_breakpoint`를 직접',
		'쓸 때는 어디에 걸었는지(file:line)를 사용자에게 보고한다 — 에디터 빨간 점에는 나타나지 않는다.',
		'',
		'**안전 규칙**: `start_project`·`continue_thread`·`step_thread`·`set_variable`은 실행(=모션)을',
		'시작·재개할 수 있는 명령이다. 시뮬레이션 모드(모터 미연결)에서만 자율 실행하고, 실기 연결 상태로',
		'보이면 실행 전에 사용자 확인을 받는다. 급정지는 `softestop`. Compile/Start 전에는 `show_threads`로',
		'같은 프로젝트의 스레드가 정지(Idle/Stopped/Error)했는지 확인한다 — 정지 미완료 상태의 Compile/Start는 제어기 이상을 유발한다.',
		'',
		'**배포 잠금**: VS Code 확장이 FTP 업로드/배포 중이면 잠금 파일(`%TEMP%/gpl-controller/<ip>.lock.json`)을 잡는다.',
		'그동안 `compile_project`·`start_project`·`unload_project`와 `controller_command`의 Compile/Start/Load/Unload는',
		'서버가 최대 20초 기다렸다 자동 진행하고, 계속 잡혀 있으면 보유자·단계·경과와 함께 거부한다(업로드 도중',
		'Compile/Start는 제어기 이상 유발). 거부되면 우회(원시 소켓, 다른 도구)하지 말고 잠시 후 재시도하거나 사용자에게 알린다.',
		'`controller_status`의 `deployLock` 필드로 현재 보유자를 볼 수 있다.',
		'',
		'**동시 접속 주의**: 1402는 사실상 단일 클라이언트 채널이다. VS Code 확장의 디버그 세션(F5 Attach)이나',
		'GDE가 같은 제어기에 붙어 작업 중이면 MCP 명령과 경합할 수 있다 — 한쪽만 사용하고, 순간 충돌로',
		'명령이 실패하면 잠시 후 한 번 재시도한다.',
		'',
		'**실시간 로그(1403)**: 아직 MCP 도구로는 노출되지 않았다. 런타임 로그 관찰이 필요하면 사용자에게',
		'VS Code 확장의 `GPL: Start Live Log Terminal` 실행을 요청하고, 그 출력을 근거로 삼는다.',
		'',
		`_이 블록은 확장 v${extensionVersion} 기준으로 생성됨. 확장 업데이트 뒤 MCP 서버 사본은 자동 갱신되지만(Claude Code에서 \`/mcp\` 재연결 필요)`,
		'이 안내 블록은 `GPL: Export AI Agent Setup`을 다시 실행해야 갱신된다. 상태 점검은 `GPL: Check AI Agent Setup`._',
		'',
		CLAUDE_SECTION_END,
	].join('\n');
}

/** 번들 사이드카(scripts/bundle-mcp.js가 기록)의 내용. */
export interface BundleBuildInfo {
	version?: string;
	builtAt?: string;
	gitSha?: string | null;
	bundled?: boolean;
}

function bundledPaths(context: vscode.ExtensionContext): { bundle: string; buildInfo: string } {
	return {
		bundle: context.asAbsolutePath(BUNDLE_RELATIVE_PATH),
		buildInfo: context.asAbsolutePath(BUILD_INFO_RELATIVE_PATH),
	};
}

function stablePaths(context: vscode.ExtensionContext): { dir: string; bundle: string; buildInfo: string } {
	const dir = path.join(context.globalStorageUri.fsPath, 'mcp');
	return {
		dir,
		bundle: path.join(dir, 'gpl-controller-mcp.cjs'),
		buildInfo: path.join(dir, 'gpl-controller-mcp.build.json'),
	};
}

function sha256Of(file: string): string | undefined {
	try {
		return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
	} catch {
		return undefined;
	}
}

function readBuildInfo(file: string): BundleBuildInfo | undefined {
	try {
		const parsed = JSON.parse(fs.readFileSync(file, 'utf8')) as BundleBuildInfo;
		return parsed && typeof parsed === 'object' ? parsed : undefined;
	} catch {
		return undefined;
	}
}

function extensionVersionOf(context: vscode.ExtensionContext): string {
	const pkg = context.extension?.packageJSON as { version?: string } | undefined;
	return String(pkg?.version ?? 'unknown');
}

/** 동봉 번들(+사이드카)을 globalStorage로 복사하고 안정 경로를 돌려준다. */
function copyBundleToStablePath(context: vscode.ExtensionContext): string {
	const src = bundledPaths(context);
	if (!fs.existsSync(src.bundle)) {
		throw new Error(
			`동봉된 MCP 서버 번들이 없습니다: ${src.bundle}` +
			(context.extensionMode === vscode.ExtensionMode.Development
				? ' — 개발 환경이면 먼저 `npm run bundle:mcp`를 실행하세요.'
				: ' — VSIX가 손상되었을 수 있습니다. 확장을 재설치하세요.')
		);
	}
	const dst = stablePaths(context);
	fs.mkdirSync(dst.dir, { recursive: true });
	fs.copyFileSync(src.bundle, dst.bundle);
	if (fs.existsSync(src.buildInfo)) {
		fs.copyFileSync(src.buildInfo, dst.buildInfo);
	} else {
		try { fs.unlinkSync(dst.buildInfo); } catch { /* 없으면 무시 */ }
	}
	return dst.bundle;
}

export type StableBundleSyncResult =
	| { action: 'absent' }
	| { action: 'bundle-missing'; detail: string }
	| { action: 'up-to-date'; stablePath: string }
	| { action: 'updated'; stablePath: string; previous?: BundleBuildInfo; current?: BundleBuildInfo }
	| { action: 'error'; detail: string };

/**
 * 활성화 시 호출: globalStorage 사본이 **있고** 동봉 번들과 내용(sha256)이 다르면 조용히 덮어쓴다(GitHub #23).
 * 사본이 없으면(Export를 실행한 적 없는 PC) 아무것도 하지 않는다. 실행 중인 MCP 프로세스는 파일을 이미 읽었으므로
 * 호출측이 "Claude Code에서 /mcp 재연결" 안내를 띄워야 한다.
 */
export function syncStableBundleIfStale(context: vscode.ExtensionContext): StableBundleSyncResult {
	const dst = stablePaths(context);
	if (!fs.existsSync(dst.bundle)) {
		return { action: 'absent' };
	}
	const src = bundledPaths(context);
	if (!fs.existsSync(src.bundle)) {
		return { action: 'bundle-missing', detail: src.bundle };
	}
	const a = sha256Of(src.bundle);
	const b = sha256Of(dst.bundle);
	if (a && b && a === b) {
		return { action: 'up-to-date', stablePath: dst.bundle };
	}
	try {
		const previous = readBuildInfo(dst.buildInfo);
		copyBundleToStablePath(context);
		return { action: 'updated', stablePath: dst.bundle, previous, current: readBuildInfo(src.buildInfo) };
	} catch (err) {
		return { action: 'error', detail: err instanceof Error ? err.message : String(err) };
	}
}

export interface AiAgentSetupReport {
	extensionVersion: string;
	bundled: { path: string; exists: boolean; sha256?: string; build?: BundleBuildInfo };
	stableCopy: { path: string; exists: boolean; sha256?: string; build?: BundleBuildInfo; upToDate: boolean | null };
	mcpJson: { path?: string; exists: boolean; registered: boolean; scriptPath?: string; scriptExists?: boolean; pointsToStableCopy: boolean | null };
	claudeMd: { path?: string; exists: boolean; hasBlock: boolean; blockVersion?: string; upToDate: boolean | null };
	/** 사람이 읽을 문제 목록(비어 있으면 정상). */
	problems: string[];
	ok: boolean;
}

function samePath(a: string, b: string): boolean {
	const na = path.normalize(path.resolve(a));
	const nb = path.normalize(path.resolve(b));
	return process.platform === 'win32' ? na.toLowerCase() === nb.toLowerCase() : na === nb;
}

/**
 * `GPL: Check AI Agent Setup` — .mcp.json 등록 경로, 사본/동봉 번들 해시 일치, CLAUDE.md 안내 블록 버전을 한 번에 보고한다(GitHub #23 ⑤).
 * 워크스페이스가 없으면 .mcp.json/CLAUDE.md 항목은 exists=false로 둔다.
 */
export function inspectAiAgentSetup(context: vscode.ExtensionContext): AiAgentSetupReport {
	const extensionVersion = extensionVersionOf(context);
	const src = bundledPaths(context);
	const dst = stablePaths(context);
	const bundled = {
		path: src.bundle,
		exists: fs.existsSync(src.bundle),
		sha256: sha256Of(src.bundle),
		build: readBuildInfo(src.buildInfo),
	};
	const stableExists = fs.existsSync(dst.bundle);
	const stableSha = stableExists ? sha256Of(dst.bundle) : undefined;
	const stableCopy = {
		path: dst.bundle,
		exists: stableExists,
		sha256: stableSha,
		build: stableExists ? readBuildInfo(dst.buildInfo) : undefined,
		upToDate: stableExists && bundled.sha256 && stableSha ? bundled.sha256 === stableSha : null,
	};

	const problems: string[] = [];
	if (!bundled.exists) {
		problems.push('동봉 MCP 번들(out/mcp/gpl-controller-mcp.cjs) 없음 — 확장 재설치 또는 `npm run bundle:mcp`');
	}

	const root = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
	const mcpJson: AiAgentSetupReport['mcpJson'] = { exists: false, registered: false, pointsToStableCopy: null };
	if (root) {
		mcpJson.path = path.join(root, '.mcp.json');
		mcpJson.exists = fs.existsSync(mcpJson.path);
		if (mcpJson.exists) {
			try {
				const cfg = JSON.parse(fs.readFileSync(mcpJson.path, 'utf8')) as { mcpServers?: Record<string, { args?: unknown[] }> };
				const entry = cfg.mcpServers?.[MCP_SERVER_NAME];
				mcpJson.registered = !!entry;
				const script = Array.isArray(entry?.args) ? entry!.args!.find((a): a is string => typeof a === 'string' && /\.c?js$/i.test(a)) : undefined;
				if (script) {
					mcpJson.scriptPath = script;
					mcpJson.scriptExists = fs.existsSync(script);
					mcpJson.pointsToStableCopy = samePath(script, dst.bundle);
				}
			} catch (err) {
				problems.push(`.mcp.json 파싱 실패: ${err instanceof Error ? err.message : String(err)}`);
			}
		}
	}

	const claudeMd: AiAgentSetupReport['claudeMd'] = { exists: false, hasBlock: false, upToDate: null };
	if (root) {
		claudeMd.path = path.join(root, 'CLAUDE.md');
		claudeMd.exists = fs.existsSync(claudeMd.path);
		if (claudeMd.exists) {
			const text = fs.readFileSync(claudeMd.path, 'utf8');
			claudeMd.hasBlock = text.includes(CLAUDE_SECTION_BEGIN);
			const m = text.match(new RegExp(`${CLAUDE_SECTION_VERSION_MARK.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*([^\\s>]+)\\s*-->`));
			claudeMd.blockVersion = m?.[1];
			claudeMd.upToDate = claudeMd.hasBlock ? claudeMd.blockVersion === extensionVersion : null;
		}
	}

	// 판정 — Export를 한 번도 실행하지 않은 워크스페이스(등록 없음·사본 없음)는 "미설정"으로만 알린다.
	const everExported = stableExists || mcpJson.registered || claudeMd.hasBlock;
	if (!everExported) {
		problems.push('AI Agent Setup 미실행 — `GPL: Export AI Agent Setup`을 실행하면 .mcp.json·CLAUDE.md·MCP 사본이 생성됨');
	} else {
		if (stableExists && stableCopy.upToDate === false) {
			problems.push(`globalStorage MCP 사본이 동봉 번들과 다름(사본 v${stableCopy.build?.version ?? '?'} / 번들 v${bundled.build?.version ?? '?'}) — 활성화 자동 갱신이 꺼져 있거나 실패`);
		}
		if (root && !mcpJson.registered) {
			problems.push('.mcp.json에 gpl-controller 등록 없음 — Export 재실행');
		}
		if (mcpJson.registered && mcpJson.scriptPath && mcpJson.scriptExists === false) {
			problems.push(`.mcp.json이 가리키는 서버 파일이 없음: ${mcpJson.scriptPath}`);
		}
		if (mcpJson.registered && mcpJson.pointsToStableCopy === false) {
			problems.push(`.mcp.json이 globalStorage 사본이 아닌 경로를 가리킴(${mcpJson.scriptPath}) — 확장 업데이트 시 깨질 수 있음, Export 재실행 권장`);
		}
		if (claudeMd.hasBlock && claudeMd.upToDate === false) {
			problems.push(`CLAUDE.md 안내 블록이 구버전(${claudeMd.blockVersion ?? '버전 표식 없음'} ≠ v${extensionVersion}) — Export 재실행`);
		}
	}

	return { extensionVersion, bundled, stableCopy, mcpJson, claudeMd, problems, ok: problems.length === 0 };
}

/** 워크스페이스 루트의 .mcp.json에 gpl-controller 항목을 병합해 쓴다(다른 서버 항목 보존). */
function writeMcpJson(workspaceRoot: string, serverScriptPath: string, opts: ExportAiAgentSetupOptions): string {
	const mcpJsonPath = path.join(workspaceRoot, '.mcp.json');
	let config: { mcpServers?: Record<string, unknown>; [key: string]: unknown } = {};
	if (fs.existsSync(mcpJsonPath)) {
		const rawText = fs.readFileSync(mcpJsonPath, 'utf8');
		try {
			config = JSON.parse(rawText);
		} catch (err) {
			throw new Error(`.mcp.json 파싱 실패 — 손상 방지를 위해 덮어쓰지 않습니다: ${err instanceof Error ? err.message : String(err)}`);
		}
	}
	const servers = (config.mcpServers && typeof config.mcpServers === 'object') ? config.mcpServers as Record<string, unknown> : {};
	servers[MCP_SERVER_NAME] = {
		type: 'stdio',
		command: 'node',
		args: [serverScriptPath],
		env: {
			GPL_HOST: opts.ip,
			GPL_PORT: String(opts.port),
			...(opts.projectName ? { GPL_PROJECT: opts.projectName } : {}),
		},
	};
	config.mcpServers = servers;
	fs.writeFileSync(mcpJsonPath, JSON.stringify(config, null, 2) + '\n');
	return mcpJsonPath;
}

/**
 * CLAUDE.md에 가드 섹션을 추가/갱신한다.
 * - 마커 블록이 있으면 그 블록만 교체(재실행 안전).
 * - 마커 없이 같은 제목의 수동 작성 섹션이 있으면 건드리지 않고 건너뛴다.
 * - 파일이 없으면 새로 만든다.
 */
function upsertClaudeMdSection(
	workspaceRoot: string,
	opts: ExportAiAgentSetupOptions,
	extensionVersion: string,
): { path: string; action: 'created' | 'updated' | 'appended' | 'skipped' } {
	const claudeMdPath = path.join(workspaceRoot, 'CLAUDE.md');
	const section = buildClaudeSection(opts, extensionVersion);

	if (!fs.existsSync(claudeMdPath)) {
		fs.writeFileSync(claudeMdPath, `# 이 프로젝트에서 AI가 지킬 규칙\n\n${section}\n`);
		return { path: claudeMdPath, action: 'created' };
	}

	const existing = fs.readFileSync(claudeMdPath, 'utf8');
	const beginIndex = existing.indexOf(CLAUDE_SECTION_BEGIN);
	const endIndex = existing.indexOf(CLAUDE_SECTION_END);

	if (beginIndex !== -1 && endIndex !== -1 && endIndex > beginIndex) {
		const before = existing.slice(0, beginIndex);
		const after = existing.slice(endIndex + CLAUDE_SECTION_END.length);
		fs.writeFileSync(claudeMdPath, before + section + after);
		return { path: claudeMdPath, action: 'updated' };
	}

	if (existing.includes(CLAUDE_SECTION_TOPIC)) {
		// 수동으로 작성된 동일 주제 섹션이 이미 있음(번호 접두 등 변형 포함) — 중복 생성하지 않는다.
		return { path: claudeMdPath, action: 'skipped' };
	}

	const separator = existing.endsWith('\n') ? '\n' : '\n\n';
	fs.writeFileSync(claudeMdPath, existing + separator + section + '\n');
	return { path: claudeMdPath, action: 'appended' };
}

export async function exportAiAgentSetup(
	context: vscode.ExtensionContext,
	opts: ExportAiAgentSetupOptions
): Promise<ExportAiAgentSetupResult> {
	const folder = vscode.workspace.workspaceFolders?.[0];
	if (!folder) {
		return { ok: false, error: 'no-workspace', detail: '열린 워크스페이스 폴더가 없습니다.' };
	}
	const workspaceRoot = folder.uri.fsPath;

	try {
		const stablePath = copyBundleToStablePath(context);
		const mcpJsonPath = writeMcpJson(workspaceRoot, stablePath, opts);
		const claudeMd = upsertClaudeMdSection(workspaceRoot, opts, extensionVersionOf(context));

		const written = [stablePath, mcpJsonPath];
		const skipped: string[] = [];
		if (claudeMd.action === 'skipped') {
			skipped.push(`${claudeMd.path} (같은 제목의 수동 작성 섹션이 이미 있어 건너뜀)`);
		} else {
			written.push(`${claudeMd.path} (${claudeMd.action})`);
		}

		void vscode.window.showInformationMessage(
			`GPL AI Agent Setup 완료 — .mcp.json${claudeMd.action === 'skipped' ? '' : ' + CLAUDE.md'} 생성/갱신. ` +
			'Claude Code 세션을 새로 시작하면 gpl-controller 도구가 활성화됩니다.'
		);

		return { ok: true, written, ...(skipped.length > 0 ? { skipped } : {}) };
	} catch (err) {
		const detail = err instanceof Error ? err.message : String(err);
		void vscode.window.showErrorMessage(`GPL AI Agent Setup 실패: ${detail}`);
		return { ok: false, error: 'export-failed', detail };
	}
}
